#!/usr/bin/env python3
# Convert input text to uppercase with line numbers
# SPDX-FileCopyrightText: 2025 yamaguchi keigo
# SPDX-License-Identifier: GPL-3.0-or-later

import sys

def main():
    n = 1
    for line in sys.stdin:
        if line == "":
            break

        line = line.rstrip("\n")

        if line == "":
            print(f"{n:>4}\t")
        else:
            print(f"{n:>4}\t{line.upper()}")
        n += 1

if __name__ == "__main__":
    main()
